Add `assert_regex`
bats-core/bats-assert pull request #43
Opened 2022-05-25 19:34 UTC by rico-chet

Add a function wrapping the commonly used [[ value =~ pattern ]]
construct, printing both operands in case of failure.

This addresses the need in #7 without affecting backward compatibility
of `assert_equal`.

2022-05-25 20:59 UTC, martin-schulze-vireso commented
I am unsure about potential code sharing with `assert_output --regex`.

2022-05-25 21:26 UTC, martin-schulze-vireso commented
Pleased add a test for the invalid regex branch.

2022-05-25 21:28 UTC, martin-schulze-vireso requested changes

2022-05-25 21:28 UTC, martin-schulze-vireso commented on src/assert_regex.bash
> +		| batslib_decorate 'ERROR: assert_output' \
This should be assert_regex?

2022-05-26 14:03 UTC, rico-chet commented
I added the error case test and fixed a copy-paste issue.

I also found that the multi-line value case needs more test coverage and documentation. It's not obvious that the assert succeeds when _any_ line of the `value` matches the `pattern`.

2022-05-26 19:44 UTC, rico-chet commented
> > It's not obvious that the assert succeeds when _any_ line of the `value` matches the `pattern`.
> 
> I would have thought that it is default regex behavior to Match anywhere in the string If there are no begin/end markers ($^).

This is the case, but I don't know by heart how multi-line stuff is handled exactly, so I added a couple characterization tests.

2022-05-26 19:50 UTC, rico-chet commented
> I am unsure about potential code sharing with `assert_output --regex`. Then again its not even 20 lines...

`assert_output` only acts on the `$output` content, but not on e.g. `$stderr` or any other data like a call trace from a mock script (the scenario where I used this last time). This is the rationale for not re-using `assert_output` for this. Also, I don't like all the parameters as they clutter tests in the long run.

2022-05-26 19:55 UTC, rico-chet commented
should be good to go now

2022-05-27 08:53 UTC, martin-schulze-vireso approved these changes

2022-05-27 09:00 UTC, martin-schulze-vireso commented
Should we also provide refute_regex in this PR?

2022-05-27 11:06 UTC, rico-chet commented on README.md
> +Multi-line value matches a single-line pattern when one of its lines matches,
I get what you mean (`\n` in the value matches `.` in the pattern) and I was confused as I don't use multi-line matching often. The message needs an improvement, I agree. I will see how fast I can do it.

2022-05-27 11:09 UTC, rico-chet commented
> Should we also provide refute_regex in this PR?

I prefer a separate PR, to keep the batch size small and get things done faster.

2022-05-28 12:46 UTC, rico-chet commented on README.md
> +Multi-line value matches a single-line pattern when one of its lines matches,
I am planning to simply refer to the Bash docs: https://www.gnu.org/software/bash/manual/html_node/Conditional-Constructs.html#:~:text=[[…]], as it's rather complicated. The applied case sensitivity should also be made visible to users, IMHO. `BASH_REMATCH` visibility should be part of a test, too.

2022-05-29 06:12 UTC, martin-schulze-vireso approved these changes

2022-05-29 07:57 UTC, merged

2022-05-29 07:57 UTC, martin-schulze-vireso commented
Thanks for your contribution.